name: Deploy to Alibaba Cloud FC

on:
  push:
    branches: [ "dev", "int", "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # 默认环境变量，可在各环境或分支中覆盖 test
  FC_MEMORY_SIZE: 128
  FC_TIMEOUT: 30
  FC_INTERNET_ACCESS: true

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    name: Deploy to Development
    runs-on: ubuntu-latest
    environment: dev
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Setup Serverless Devs
      run: npm install -g @serverless-devs/s

    - name: Configure Serverless Devs
      run: s config add --AccessKeyID ${{ secrets.DEV_AUTOMATION_AK }} --AccessKeySecret ${{ secrets.DEV_AUTOMATION_SK }} -a default -f

    # - name: Clean Serverless Devs Cache
    #   run: s clean --all

    # - name: Debug Environment Variables
    #   run: |
    #     echo "=== Current Directory ==="
    #     pwd
    #     ls -la
    #     echo "=== Pipeline Callback FC Directory ==="
    #     ls -la pipeline-callback-fc/
    #     echo "=== Environment Variables ==="
    #     echo "FC_NAME: $FC_NAME"
    #     echo "FC_REGION: $FC_REGION"
    #     echo "FC_MEMORY_SIZE: $FC_MEMORY_SIZE"
    #     echo "FC_TIMEOUT: $FC_TIMEOUT"
    #     echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"

    - name: Deploy to Dev Environment
      working-directory: ./pipeline-callback-fc
      env:
        FC_NAME: simple-python-function-dev
        FC_REGION: ${{ vars.FC_REGION || 'cn-beijing' }}
        FC_MEMORY_SIZE: ${{ vars.FC_MEMORY_SIZE || '128' }}
        FC_TIMEOUT: ${{ vars.FC_TIMEOUT || '30' }}
        FC_INTERNET_ACCESS: ${{ vars.FC_INTERNET_ACCESS || 'true' }}
        GITHUB_REF_NAME: dev
      run: |
        echo "Deploying with environment variables:"
        echo "FC_NAME: $FC_NAME"
        echo "FC_REGION: $FC_REGION"
        echo "FC_MEMORY_SIZE: $FC_MEMORY_SIZE"
        # s deploy -y -t ./pipeline-callback-fc/s.yaml
        s deploy -y 

  deploy-int:
    if: github.ref == 'refs/heads/int'
    name: Deploy to Integration
    runs-on: ubuntu-latest
    environment: int
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Setup Serverless Devs
      run: npm install -g @serverless-devs/s

    - name: Configure Serverless Devs
      run: s config add --AccessKeyID ${{ secrets.DEV_AUTOMATION_AK }} --AccessKeySecret ${{ secrets.DEV_AUTOMATION_SK }} -a default -f

    - name: Clean Serverless Devs Cache
      run: s clean --all

    - name: Debug Environment Variables
      run: |
        echo "=== Environment Variables ==="
        echo "FC_NAME: $FC_NAME"
        echo "FC_REGION: $FC_REGION"
        echo "FC_MEMORY_SIZE: $FC_MEMORY_SIZE"
        echo "FC_TIMEOUT: $FC_TIMEOUT"
        echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"

    - name: Deploy to Int Environment
      env:
        FC_NAME: simple-python-function-int
        FC_REGION: ${{ vars.FC_REGION || 'cn-beijing' }}
        FC_MEMORY_SIZE: ${{ vars.FC_MEMORY_SIZE || '256' }}
        FC_TIMEOUT: ${{ vars.FC_TIMEOUT || '60' }}
        FC_INTERNET_ACCESS: ${{ vars.FC_INTERNET_ACCESS || 'true' }}
        GITHUB_REF_NAME: int
      run: s deploy -y -t ./pipeline-callback-fc/s.yaml

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    name: Deploy to Production
    runs-on: ubuntu-latest
    environment: prod
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Setup Serverless Devs
      run: npm install -g @serverless-devs/s

    - name: Configure Serverless Devs
      run: s config add --AccessKeyID ${{ secrets.DEV_AUTOMATION_AK }} --AccessKeySecret ${{ secrets.DEV_AUTOMATION_SK }} -a default -f

    - name: Clean Serverless Devs Cache
      run: s clean --all

    - name: Debug Environment Variables
      run: |
        echo "=== Environment Variables ==="
        echo "FC_NAME: $FC_NAME"
        echo "FC_REGION: $FC_REGION"
        echo "FC_MEMORY_SIZE: $FC_MEMORY_SIZE"
        echo "FC_TIMEOUT: $FC_TIMEOUT"
        echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"

    - name: Deploy to Prod Environment
      env:
        FC_NAME: simple-python-function-prod
        FC_REGION: ${{ vars.FC_REGION || 'cn-beijing' }}
        FC_MEMORY_SIZE: ${{ vars.FC_MEMORY_SIZE || '512' }}
        FC_TIMEOUT: ${{ vars.FC_TIMEOUT || '60' }}
        FC_INTERNET_ACCESS: ${{ vars.FC_INTERNET_ACCESS || 'true' }}
        GITHUB_REF_NAME: main
      run: s deploy -y -t ./pipeline-callback-fc/s.yaml
