name: Deploy to Alibaba Cloud FC

on:
  push:
    branches: [ "dev", "int", "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # 默认环境变量，可在各环境或分支中覆盖
  FC_MEMORY_SIZE: 128
  FC_TIMEOUT: 30
  FC_INTERNET_ACCESS: true

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    name: Deploy to Development
    runs-on: standard-ghc
    environment: dev
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Serverless Devs
      uses: aliyun/setup-serverless-devs@v1
      with:
        access-key-id: ${{ secrets.DEV_AUTOMATION_AK }}
        access-key-secret: ${{ secrets.DEV_AUTOMATION_SK }}

    - name: Deploy to Dev Environment
      env:
        FC_NAME: simple-python-function-dev
        FC_REGION: ${{ vars.FC_REGION || 'cn-beijing' }}
        FC_MEMORY_SIZE: ${{ vars.FC_MEMORY_SIZE || '128' }}
        FC_TIMEOUT: ${{ vars.FC_TIMEOUT || '30' }}
        FC_INTERNET_ACCESS: ${{ vars.FC_INTERNET_ACCESS || 'true' }}
      run: s deploy -y

  deploy-int:
    if: github.ref == 'refs/heads/int'
    name: Deploy to Integration
    runs-on: standard-ghc
    environment: int
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Serverless Devs
      uses: aliyun/setup-serverless-devs@v1
      with:
        access-key-id: ${{ secrets.DEV_AUTOMATION_AK }}
        access-key-secret: ${{ secrets.DEV_AUTOMATION_SK }}

    - name: Deploy to Int Environment
      env:
        FC_NAME: simple-python-function-int
        FC_REGION: ${{ vars.FC_REGION || 'cn-beijing' }}
        FC_MEMORY_SIZE: ${{ vars.FC_MEMORY_SIZE || '256' }}
        FC_TIMEOUT: ${{ vars.FC_TIMEOUT || '60' }}
        FC_INTERNET_ACCESS: ${{ vars.FC_INTERNET_ACCESS || 'true' }}
      run: s deploy -y

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    name: Deploy to Production
    runs-on: standard-ghc
    environment: prod
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Serverless Devs
      uses: aliyun/setup-serverless-devs@v1
      with:
        access-key-id: ${{ secrets.DEV_AUTOMATION_AK }}
        access-key-secret: ${{ secrets.DEV_AUTOMATION_SK }}

    - name: Deploy to Prod Environment
      env:
        FC_NAME: simple-python-function-prod
        FC_REGION: ${{ vars.FC_REGION || 'cn-beijing' }}
        FC_MEMORY_SIZE: ${{ vars.FC_MEMORY_SIZE || '512' }}
        FC_TIMEOUT: ${{ vars.FC_TIMEOUT || '60' }}
        FC_INTERNET_ACCESS: ${{ vars.FC_INTERNET_ACCESS || 'true' }}
      run: s deploy -y
