name: Deploy to Alibaba Cloud FC

on:
  workflow_dispatch:
  push:
    branches: [ "dev", "int", "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    name: Deploy to Development
    runs-on: ubuntu-latest
    environment: dev
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
        
    - name: Setup Serverless Devs
      run: npm install -g @serverless-devs/s
      

    - name: Configure Serverless Devs
      run: s config add --AccessKeyID ${{ secrets.DEV_AUTOMATION_AK }} --AccessKeySecret ${{ secrets.DEV_AUTOMATION_SK }} -a default -f


    - name: Deploy to Dev Environment
      working-directory: ./pipeline-callback-fc
      run: |
        s deploy -y 

